backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "catalogo"
    label: "Catálogo"
    files:
      - file: "productos.json"
        label: "Lista de Productos"
        name: "lista_productos"
        fields:
          - label: "Productos"
            name: "productos"
            widget: "list"
            summary: "{{fields.nombre}}"
            fields:
              - label: "ID"
                name: "id"
                widget: "string"
              - label: "Nombre"
                name: "nombre"
                widget: "string"
              - label: "Precio CLP"
                name: "precio"
                widget: "number"
              - label: "Stock"
                name: "stock"
                widget: "number"
              - label: "Imagen del Producto"
                name: "imagen"
                widget: "image"
